name: CI/CD Pipeline #name of the workflow

on:
    push:
        branches: [main] # this workflow will run everytime there is a push to the main branch
    workflow_dispatch: # this allows you to manually trigger the workflow from the GitHub UI

jobs: 
    build-and-test:
        runs-on: ubuntu-latest # this will start a job and name it "build-and-test"
        # it will run on a virtual Linux server which is called ubuntu-latest

        steps:
            - uses: actions/checkout@v3 # this will checkout the code from the repo
            - name: Set up Python # this will install Python 3.10 on the Virtual Server
              uses: actions/setup-python@v4
              with: 
                python-version: '3.10' 
            - name: Install dependencies # this install all the dependencies from the requirements.txt file to the virtual server
              run: |
                    python -m pip install -upgrade pip
                    pip install -r requirements.txt 
            - name: Run tests # this installs pytest (python testing tool) and runs the test app
              run: |
                    pip install pytest
                    pytest test_app.py
